feat: Add support for nginx 1.22 (#4)

diff --git a/build-rpm b/build-rpm
--- a/build-rpm
+++ b/build-rpm
@@ -9,7 +9,7 @@ set -u
 
 export LC_ALL=C
 
-BUILD_PACKAGES="autoconf automake libtool gcc make rpm-build rpmdevtools"
+BUILD_PACKAGES="autoconf automake libtool gcc make procps-ng rpm-build rpmdevtools"
 MAX_RETRY="10"
 
 if [[ $# -lt 2 ]]; then
@@ -33,43 +33,42 @@ fi
 RPM_DIST=.$(egrep -o "^%el[0-9]*" "${RPM_MACROS}" | tr -d '%')
 echo "RPM_DIST: ${RPM_DIST} (${RPM_MACROS})"
 
-# install nginx and setup spec file
+# Install nginx and setup spec file
 echo
 echo "Installing nginx"
 PACKAGE_MANAGER="dnf"
-if [[ "${RPM_DIST}" = ".el9" ]]; then
-    # el9 or later
-    dnf -y install nginx
-elif [[ "${RPM_DIST}" = ".el8" ]]; then
-    # el8
-
-    # check module version
-    if [[ -z "${MODULE_VERSION}" ]]; then
-        echo "Error: MODULE_VERSION is required for el8 or later"
-        exit 1
-    fi
-
-    # install epel-release
-    if [[ "${REPOSITORY}" = "epel-modular" ]]; then
-        dnf -y install epel-release
-        dnf clean all
-    fi
-
-    # install nginx
-    echo
-    dnf -y module reset nginx
-    echo "Installing nginx:${MODULE_VERSION} on ${REPOSITORY}"
-    dnf -y module install nginx:${MODULE_VERSION}/common
-else
+if [[ "${RPM_DIST}" = ".el7" ]]; then
     PACKAGE_MANAGER="yum"
     yum -y install epel-release
     yum -y install nginx
+else
+    if [[ -z "${REPOSITORY}" ]]; then
+        # Non-modular package version
+        dnf -y install nginx
+    else
+        # Modular package version
+        if [[ -z "${MODULE_VERSION}" ]]; then
+            echo "Error: MODULE_VERSION is required for el8 or later"
+            exit 1
+        fi
+
+        # EPEL 8 Modularity was going away on February 15, 2023
+        if [[ "${REPOSITORY}" = "epel-modular" ]]; then
+            dnf -y install epel-release
+            dnf config-manager --enable epel-modular
+            dnf clean all
+        fi
+
+        dnf -y module reset nginx
+        echo "Installing nginx:${MODULE_VERSION} on ${REPOSITORY}"
+        dnf -y module install nginx:${MODULE_VERSION}/common
+    fi
 fi
 # 1:1.20.0-2.module_el8.5.0+899+43b718f6 -> 1.20.0
 NGINX_VERSION=$(${PACKAGE_MANAGER} list -q nginx | grep nginx.x86_64 | awk '{ print $2 }' | grep -oP '(?<=:).+(?=-)')
 sed -e "s/@NGINX_VERSION@/${NGINX_VERSION}/g" "SPECS/${SPEC_FILE_NAME}.in" > "SPECS/${SPEC_FILE_NAME}"
 
-# install dependencies
+# Install dependencies
 if [[ -f /usr/bin/dnf ]]; then
     # el8 or later
     echo
@@ -104,7 +103,7 @@ else
     done
 fi
 
-# build rpm
+# Build RPM files
 if [[ ! -d SOURCES ]]; then
     mkdir SOURCES
 fi
@@ -117,11 +116,13 @@ else
     spectool -g -A "SPECS/${SPEC_FILE_NAME}" -C SOURCES/
 fi
 
-echo "Building RPM:"
-if [[ "${REPOSITORY}" = "epel-modular" ]]; then
-    RPM_DIST=$(echo "${RPM_DIST}" | sed -r "s/^\.(.*)/.module_\1.epel.${MODULE_VERSION}/")
-else
-    RPM_DIST=$(echo "${RPM_DIST}" | sed -r "s/^\.(.*)/.module_\1.${MODULE_VERSION}/")
+echo "Building RPM files:"
+if [[ ! -z "${REPOSITORY}" ]]; then
+    if [[ "${REPOSITORY}" = "epel-modular" ]]; then
+        RPM_DIST=$(echo "${RPM_DIST}" | sed -r "s/^\.(.*)/.module_\1.epel.${MODULE_VERSION}/")
+    else
+        RPM_DIST=$(echo "${RPM_DIST}" | sed -r "s/^\.(.*)/.module_\1.${MODULE_VERSION}/")
+    fi
 fi
 rpmbuild \
     --define "%_topdir ${RPMBUILD_DIR}" \
@@ -129,4 +130,3 @@ rpmbuild \
     -ba "SPECS/${SPEC_FILE_NAME}"
 
 popd
-
