fix: drop CentOS 7 support

diff --git a/build-rpm b/build-rpm
--- a/build-rpm
+++ b/build-rpm
@@ -29,7 +29,7 @@ pushd "${RPMBUILD_DIR}"
 # RPM macros
 RPM_MACROS=/usr/lib/rpm/macros.d/macros.dist
 if [[ -f /etc/rpm/macros.dist ]]; then
-    # el7 and el8
+    # el8
     RPM_MACROS=/etc/rpm/macros.dist
 fi
 RPM_DIST=.$(egrep -o "^%el[0-9]*" "${RPM_MACROS}" | tr -d '%')
@@ -38,41 +38,29 @@ echo "RPM_DIST: ${RPM_DIST} (${RPM_MACROS})"
 # Install nginx and setup spec file
 echo
 echo "Installing nginx"
-PACKAGE_MANAGER="dnf"
-if [[ "${RPM_DIST}" = ".el7" ]]; then
-    PACKAGE_MANAGER="yum"
-    yum -y install epel-release
-    yum -y install nginx
-    ARCH=$(arch)
-    if [[ "${ARCH}" == "aarch64" ]]; then
-        # Required only for el7 + aarch64
-        yum -y install GeoIP-devel
-    fi
+if [[ -z "${REPOSITORY}" ]]; then
+    # Non-modular package version
+    dnf -y install nginx
 else
-    if [[ -z "${REPOSITORY}" ]]; then
-        # Non-modular package version
-        dnf -y install nginx
-    else
-        # Modular package version
-        if [[ -z "${MODULE_VERSION}" ]]; then
-            echo "Error: MODULE_VERSION is required for el8 or later"
-            exit 1
-        fi
-
-        # EPEL 8 Modularity was going away on February 15, 2023
-        if [[ "${REPOSITORY}" = "epel-modular" ]]; then
-            dnf -y install epel-release
-            dnf config-manager --enable epel-modular
-            dnf clean all
-        fi
-
-        dnf -y module reset nginx
-        echo "Installing nginx:${MODULE_VERSION} on ${REPOSITORY}"
-        dnf -y module install nginx:${MODULE_VERSION}/common
+    # Modular package version
+    if [[ -z "${MODULE_VERSION}" ]]; then
+        echo "Error: MODULE_VERSION is required for el8 or later"
+        exit 1
     fi
+
+    # EPEL 8 Modularity was going away on February 15, 2023
+    if [[ "${REPOSITORY}" = "epel-modular" ]]; then
+        dnf -y install epel-release
+        dnf config-manager --enable epel-modular
+        dnf clean all
+    fi
+
+    dnf -y module reset nginx
+    echo "Installing nginx:${MODULE_VERSION} on ${REPOSITORY}"
+    dnf -y module install nginx:${MODULE_VERSION}/common
 fi
 # 1:1.20.0-2.module_el8.5.0+899+43b718f6 -> 1.20.0
-NGINX_VERSION=$(${PACKAGE_MANAGER} list -q nginx | grep nginx. | awk '{ print $2 }' | grep -oP '(?<=:).+(?=-)')
+NGINX_VERSION=$(dnf list -q nginx | grep nginx. | awk '{ print $2 }' | grep -oP '(?<=:).+(?=-)')
 sed -e "s/@NGINX_VERSION@/${NGINX_VERSION}/g" "SPECS/${SPEC_FILE_NAME}.in" > "SPECS/${SPEC_FILE_NAME}"
 
 # Install dependencies
@@ -93,21 +81,6 @@ if [[ -f /usr/bin/dnf ]]; then
         echo
         echo "Retry: dnf -y builddep \"SPECS/${SPEC_FILE_NAME}\" (retry: ${RETRY})"
     done
-else
-    echo
-    echo "Installing build tools and dependencies: ${BUILD_PACKAGES}"
-    until yum -y install ${BUILD_PACKAGES} || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
-    do
-        sleep $((RETRY++))
-        echo
-        echo "Retry: yum -y install ${BUILD_PACKAGES} (retry: ${RETRY})"
-    done
-    until yum-builddep -y "SPECS/${SPEC_FILE_NAME}" || [[ "${RETRY}" -eq "${MAX_RETRY}" ]];
-    do
-        sleep $((RETRY++))
-        echo
-        echo "Retry: yum-builddep -y \"SPECS/${SPEC_FILE_NAME}\" (retry: ${RETRY})"
-    done
 fi
 
 # Build RPM files
@@ -119,7 +92,7 @@ if [[ "${RPM_DIST}" = ".el9" ]]; then
     # el9 or later
     spectool -g -a "SPECS/${SPEC_FILE_NAME}" -C SOURCES/
 else
-    # el7 or el8
+    # el8
     spectool -g -A "SPECS/${SPEC_FILE_NAME}" -C SOURCES/
 fi
 
